[package]
name = "sctk-test-clients"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"

[dependencies.sctk]
package = "smithay-client-toolkit"
git = "https://github.com/Smithay/client-toolkit.git"
# ext-background-effect merged
rev = "99ddfec6bc68d3a5d47d9554f973b34aebab0b83"

[[bin]]
name = "dmabuf_y_invert"
path = "src/dmabuf_y_invert.rs"

[[bin]]
name = "popup_background_effect"
path = "src/popup_background_effect.rs"

[[bin]]
name = "subsurface_no_geometry"
path = "src/subsurface_no_geometry.rs"

[[bin]]
name = "layer_shell_popups"
path = "src/layer_shell_popups.rs"

[[bin]]
name = "blur_region_switch_half"
path = "src/blur_region_switch_half.rs"

[[bin]]
name = "background_layer_frame_callbacks"
path = "src/background_layer_frame_callbacks.rs"

[[bin]]
name = "fullscreen_on_disabled_output"
path = "src/fullscreen_on_disabled_output.rs"

[[bin]]
name = "pointer_lock_position_hint"
path = "src/pointer_lock_position_hint.rs"
